;;; gptel-otel-langfuse-mcp-test.el --- Optional Langfuse MCP tests  -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(defvar gptel--known-tools)
(defvar mcp-server-connections)
(require 'gptel-otel-langfuse-mcp)

(defmacro gptel-otel-langfuse-mcp-test--isolated (&rest body)
  `(let ((gptel-otel-langfuse-mcp-mode nil)
         (gptel-otel-langfuse-mcp--generation 0)
         (gptel-otel-langfuse-mcp--connection nil)
         (gptel-otel-langfuse-mcp--discovery-timer nil)
         (gptel-otel-langfuse-mcp-timeout 1)
         (gptel--known-tools '(("other" ("existing" . existing-tool))))
         (mcp-server-connections (make-hash-table :test #'equal)))
     (cl-letf (((symbol-function 'gptel-agent-update) (lambda () nil)))
       (unwind-protect (progn ,@body)
         (when (timerp gptel-otel-langfuse-mcp--discovery-timer)
           (cancel-timer gptel-otel-langfuse-mcp--discovery-timer))))))

(defun gptel-otel-langfuse-mcp-test--tools (&optional omit)
  (mapcar (lambda (name) (list :name name))
          (delete omit (copy-sequence gptel-otel-langfuse-mcp--tool-names))))

(defun gptel-otel-langfuse-mcp-test--make-tool (&rest spec)
  "Faithful isolated gptel-make-tool registry stub."
  (let* ((name (plist-get spec :name))
         (category (plist-get spec :category))
         (tool (list :gptel-tool name)))
    (unless (and (stringp name) (stringp category))
      (error "gptel tool names and categories must be strings"))
    (let ((entry (assoc category gptel--known-tools)))
      (if entry
          (setcdr entry (cons (cons name tool) (cdr entry)))
        (push (cons category (list (cons name tool))) gptel--known-tools)))
    tool))

(defun gptel-otel-langfuse-mcp-test--registry-names ()
  (mapcar #'car (cdr (assoc "langfuse-read" gptel--known-tools))))

(ert-deftest gptel-otel-langfuse-mcp-registers-read-tools-async ()
  (gptel-otel-langfuse-mcp-test--isolated
   (let ((real-require (symbol-function 'require))
         connect-args callback async-args
         (gptel-otel-langfuse-base-url "https://langfuse.test/")
         (gptel-otel-langfuse-auth-function (lambda () '("public" . "secret"))))
     (cl-letf (((symbol-function 'require)
                (lambda (feature &optional _filename noerror)
                  (if (memq feature '(mcp gptel)) t
                    (funcall real-require feature nil noerror)))
               ((symbol-function 'mcp-connect-server)
                (lambda (&rest args)
                  (setq connect-args args
                        callback (plist-get (cdr args) :tools-callback))
                  (puthash "langfuse" 'connection mcp-server-connections)
                  'connection))
               ((symbol-function 'mcp-make-text-tool)
                (lambda (server name &optional async)
                  (push (list server name async) async-args)
                  (list :name name :function #'ignore)))
               ((symbol-function 'gptel-make-tool)
                #'gptel-otel-langfuse-mcp-test--make-tool)
               ((symbol-function 'mcp-stop-server) (lambda (_name) nil)))
       (gptel-otel-langfuse-mcp-mode 1)
       (should (equal "https://langfuse.test/api/public/mcp"
                      (plist-get (cdr connect-args) :url)))
       (should (equal "Basic cHVibGljOnNlY3JldA=="
                      (cdr (assoc "Authorization"
                                  (plist-get (cdr connect-args) :headers)))))
       (funcall callback 'connection (gptel-otel-langfuse-mcp-test--tools))
       (should (assoc "langfuse-read" gptel--known-tools))
       (should (equal (sort (copy-sequence gptel-otel-langfuse-mcp--tool-names)
                            #'string<)
                      (sort (gptel-otel-langfuse-mcp-test--registry-names)
                            #'string<)))
       (should (cl-every (lambda (args) (eq (nth 2 args) t)) async-args))
       (should (equal '(("other" ("existing" . existing-tool)))
                      (cl-remove-if (lambda (entry) (equal (car entry) "langfuse-read"))
                                    gptel--known-tools))))))))

(ert-deftest gptel-otel-langfuse-mcp-registers-with-real-gptel-tool-registry ()
  "Use gptel's actual registration API, retaining only MCP transport mocks."
  (skip-unless (require 'gptel nil t))
  (gptel-otel-langfuse-mcp-test--isolated
   (let ((gptel-otel-langfuse-base-url "https://langfuse.test")
         (gptel-otel-langfuse-auth-function (lambda () '("pk" . "sk")))
         callback)
     (cl-letf (((symbol-function 'require)
                (let ((real-require (symbol-function 'require)))
                  (lambda (feature &optional filename noerror)
                    (if (eq feature 'mcp)
                        t
                      (funcall real-require feature filename noerror)))))
               ((symbol-function 'mcp-connect-server)
                (lambda (&rest args)
                  (setq callback (plist-get (cdr args) :tools-callback))
                  (puthash "langfuse" 'connection mcp-server-connections)
                  ;; mcp-connect-server returns its startup timer, not the
                  ;; registered connection, in the asynchronous implementation.
                  'startup-timer))
               ((symbol-function 'mcp-make-text-tool)
                (lambda (_server name async)
                  (list :name name
                        :function (lambda (&rest _args) nil)
                        :description (format "Read Langfuse %s" name)
                        :args nil :async async)))
               ((symbol-function 'mcp-stop-server) (lambda (_name) nil))
               ((symbol-function 'gptel-agent-update) (lambda () nil)))
       (gptel-otel-langfuse-mcp-mode 1)
       (funcall callback 'connection (gptel-otel-langfuse-mcp-test--tools))
       (let ((tools (gptel-get-tool "langfuse-read")))
         (should (= 7 (length tools)))
         (should (equal (sort (copy-sequence gptel-otel-langfuse-mcp--tool-names)
                              #'string<)
                        (sort (mapcar #'gptel-tool-name tools) #'string<)))
         (dolist (name gptel-otel-langfuse-mcp--tool-names)
           (let ((tool (gptel-get-tool (list "langfuse-read" name))))
             (should (gptel-tool-p tool))
             (should (gptel-tool-async tool))))
         (should-error
          (gptel-get-tool '("langfuse-read" "deleteObservation"))))))))

(ert-deftest gptel-otel-langfuse-mcp-rejects-extra-advertised-write-tools ()
  (gptel-otel-langfuse-mcp-test--isolated
   (let (callback made
         (gptel-otel-langfuse-base-url "https://langfuse.test")
         (gptel-otel-langfuse-auth-function (lambda () '("pk" . "sk"))))
     (cl-letf (((symbol-function 'require) (lambda (&rest _args) t))
               ((symbol-function 'mcp-connect-server)
                (lambda (&rest args)
                  (setq callback (plist-get (cdr args) :tools-callback))
                  (puthash "langfuse" 'connection mcp-server-connections) 'connection))
               ((symbol-function 'mcp-make-text-tool)
                (lambda (_server name &optional _async) (push name made) (list :name name)))
               ((symbol-function 'gptel-make-tool)
                #'gptel-otel-langfuse-mcp-test--make-tool)
               ((symbol-function 'mcp-stop-server) (lambda (_name) nil)))
       (gptel-otel-langfuse-mcp-mode 1)
       (funcall callback 'connection
                (append (gptel-otel-langfuse-mcp-test--tools)
                        (list (list :name "deleteObservation"))))
       (should (equal (sort (copy-sequence gptel-otel-langfuse-mcp--tool-names) #'string<)
                      (sort (gptel-otel-langfuse-mcp-test--registry-names) #'string<)))
       (should-not (member "deleteObservation" made))))))

(ert-deftest gptel-otel-langfuse-mcp-fails-without-mcp-dependency ()
  (gptel-otel-langfuse-mcp-test--isolated
   (let (diagnostics
         (gptel-otel-langfuse-base-url "https://langfuse.test"))
     (cl-letf (((symbol-function 'require)
                (lambda (feature &optional _filename _noerror)
                  (not (eq feature 'mcp))))
               ((symbol-function 'gptel-otel-langfuse-mcp--report)
                (lambda (text) (push text diagnostics))))
       (gptel-otel-langfuse-mcp-mode 1)
       (should-not gptel-otel-langfuse-mcp-mode)
       (should (equal '("missing required MCP or gptel dependency") diagnostics))))))

(ert-deftest gptel-otel-langfuse-mcp-auth-errors-disable-mode ()
  (gptel-otel-langfuse-mcp-test--isolated
   (let (diagnostics
         (gptel-otel-langfuse-base-url "https://langfuse.test")
         (gptel-otel-langfuse-auth-function
          (lambda () (error "auth source unavailable"))))
     (cl-letf (((symbol-function 'require) (lambda (&rest _args) t))
               ((symbol-function 'gptel-otel-langfuse-mcp--report)
                (lambda (text) (push text diagnostics))))
       (gptel-otel-langfuse-mcp-mode 1)
       (should-not gptel-otel-langfuse-mcp-mode)
       (should-not (gethash "langfuse" mcp-server-connections))
       (should (equal '("MCP initialization failed") diagnostics))))))

(ert-deftest gptel-otel-langfuse-mcp-timeout-disables-and-cleans-up ()
  (gptel-otel-langfuse-mcp-test--isolated
   (let (timeout-function diagnostics
         (gptel-otel-langfuse-base-url "https://langfuse.test")
         (gptel-otel-langfuse-auth-function (lambda () '("pk" . "sk"))))
     (cl-letf (((symbol-function 'require) (lambda (&rest _args) t))
               ((symbol-function 'mcp-connect-server)
                (lambda (&rest _args)
                  (puthash "langfuse" 'connection mcp-server-connections) 'connection))
               ((symbol-function 'run-at-time)
                (lambda (_seconds _repeat function) (setq timeout-function function) 'timer))
               ((symbol-function 'timerp) (lambda (_timer) nil))
               ((symbol-function 'mcp-stop-server) (lambda (_name) nil))
               ((symbol-function 'gptel-otel-langfuse-mcp--report)
                (lambda (text) (push text diagnostics))))
       (gptel-otel-langfuse-mcp-mode 1)
       (funcall timeout-function)
       (should-not gptel-otel-langfuse-mcp-mode)
       (should-not (gethash "langfuse" mcp-server-connections))
       (should (equal '("MCP tool discovery timed out") diagnostics))))))

(ert-deftest gptel-otel-langfuse-mcp-auth-is-once-per-enable-and-restart ()
  (gptel-otel-langfuse-mcp-test--isolated
   (let* ((calls 0) connections
         (real-require (symbol-function 'require))
         (gptel-otel-langfuse-base-url "https://langfuse.test")
         (gptel-otel-langfuse-auth-function
          (lambda () (cl-incf calls) '("pk" . "sk"))))
     (cl-letf (((symbol-function 'require)
                (lambda (feature &optional filename noerror)
                  (if (memq feature '(mcp gptel)) t
                    (funcall real-require feature filename noerror))))
               ((symbol-function 'mcp-connect-server)
                (lambda (&rest _args)
                  (let ((connection (make-symbol "connection")))
                    (push connection connections)
                    (puthash "langfuse" connection mcp-server-connections)
                    connection)))
               ((symbol-function 'mcp-stop-server) (lambda (_name) nil)))
       (gptel-otel-langfuse-mcp-mode 1)
       (gptel-otel-langfuse-mcp-mode 1)
       (should (= calls 2))))))

(ert-deftest gptel-otel-langfuse-mcp-preserves-unrelated-string-state ()
  (gptel-otel-langfuse-mcp-test--isolated
   (let ((other-connection 'other-connection)
         (gptel-otel-langfuse-mcp--category "langfuse-read")
         (gptel--known-tools '(("langfuse-read" ("stale" . stale))
                                ("other" ("existing" . existing-tool))))
         (gptel-otel-langfuse-base-url "https://langfuse.test")
         (gptel-otel-langfuse-auth-function (lambda () '("pk" . "sk"))))
     (puthash "other" other-connection mcp-server-connections)
     (cl-letf (((symbol-function 'require) (lambda (&rest _args) t))
               ((symbol-function 'mcp-connect-server)
                (lambda (&rest _args)
                  (puthash "langfuse" 'connection mcp-server-connections) 'connection))
               ((symbol-function 'mcp-stop-server) (lambda (_name) nil)))
       (gptel-otel-langfuse-mcp-mode 1)
       (gptel-otel-langfuse-mcp-mode -1)
       (should (eq other-connection (gethash "other" mcp-server-connections)))
       (should (equal '("other" ("existing" . existing-tool))
                      (assoc "other" gptel--known-tools)))))))

(ert-deftest gptel-otel-langfuse-mcp-ignores-stale-and-replaced-connections ()
  (gptel-otel-langfuse-mcp-test--isolated
   (let (callbacks connections
         (gptel-otel-langfuse-base-url "https://langfuse.test")
         (gptel-otel-langfuse-auth-function (lambda () '("pk" . "sk"))))
     (cl-letf (((symbol-function 'require) (lambda (&rest _args) t))
               ((symbol-function 'mcp-connect-server)
                (lambda (&rest args)
                  (let ((connection (make-symbol "connection")))
                    (push (plist-get (cdr args) :tools-callback) callbacks)
                    (push connection connections)
                    (puthash "langfuse" connection mcp-server-connections)
                    connection)))
               ((symbol-function 'mcp-make-text-tool)
                (lambda (_server name &optional _async) (list :name name)))
               ((symbol-function 'gptel-make-tool)
                #'gptel-otel-langfuse-mcp-test--make-tool)
               ((symbol-function 'mcp-stop-server) (lambda (_name) nil)))
       (gptel-otel-langfuse-mcp-mode 1)
       (let ((old-callback (car callbacks))
             (old-connection (car connections)))
         (gptel-otel-langfuse-mcp-mode 1)
         (funcall old-callback old-connection (gptel-otel-langfuse-mcp-test--tools))
         (should-not (assoc "langfuse-read" gptel--known-tools))
         (puthash "langfuse" 'external-replacement mcp-server-connections)
         (funcall (car callbacks) (car connections)
                  (gptel-otel-langfuse-mcp-test--tools))
         (should-not (assoc "langfuse-read" gptel--known-tools)))))))

(ert-deftest gptel-otel-langfuse-mcp-connect-and-callback-errors-clean-up ()
  (gptel-otel-langfuse-mcp-test--isolated
   (let (callback diagnostics
         (gptel-otel-langfuse-base-url "https://langfuse.test")
         (gptel-otel-langfuse-auth-function (lambda () '("pk" . "sk"))))
     (cl-letf (((symbol-function 'require) (lambda (&rest _args) t))
               ((symbol-function 'mcp-connect-server)
                (lambda (&rest _args)
                  (puthash "langfuse" 'connection mcp-server-connections)
                  (error "synchronous failure")))
               ((symbol-function 'mcp-stop-server) (lambda (_name) nil))
               ((symbol-function 'gptel-otel-langfuse-mcp--report)
                (lambda (text) (push text diagnostics))))
       (gptel-otel-langfuse-mcp-mode 1)
       (should-not gptel-otel-langfuse-mcp-mode)
       (should-not (gethash "langfuse" mcp-server-connections))
       (should (equal '("MCP initialization failed") diagnostics)))
     (setq diagnostics nil)
     (cl-letf (((symbol-function 'require) (lambda (&rest _args) t))
               ((symbol-function 'mcp-connect-server)
                (lambda (&rest args)
                  (setq callback (plist-get (cdr args) :tools-callback))
                  (puthash "langfuse" 'connection mcp-server-connections) 'connection))
               ((symbol-function 'mcp-make-text-tool)
                (lambda (&rest _args) (error "tool failure")))
               ((symbol-function 'mcp-stop-server) (lambda (_name) nil))
               ((symbol-function 'gptel-otel-langfuse-mcp--report)
                (lambda (text) (push text diagnostics))))
       (gptel-otel-langfuse-mcp-mode 1)
       (funcall callback 'connection (gptel-otel-langfuse-mcp-test--tools))
       (should-not gptel-otel-langfuse-mcp-mode)
       (should-not (gethash "langfuse" mcp-server-connections))
       (should (equal '("MCP tool discovery failed") diagnostics))))))

;;; gptel-otel-langfuse-mcp-test.el ends here.
