;;; gptel-otel-transport-test.el --- Transport tests  -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'gptel-otel-transport)

(defmacro gptel-otel-test--with-spool (&rest body)
  `(let* ((dir (make-temp-file "gptel-otel-test" t))
          (gptel-otel-spool-directory dir)
          (gptel-otel--delivery-active nil)
          (gptel-otel--delivery-timer nil)
          (gptel-otel--watchdog-timer nil))
     (unwind-protect (progn ,@body)
       (when (timerp gptel-otel--delivery-timer) (cancel-timer gptel-otel--delivery-timer))
       (when (timerp gptel-otel--watchdog-timer) (cancel-timer gptel-otel--watchdog-timer))
       (delete-directory dir t))))

(defun gptel-otel-test--request (&optional payload)
  (let ((span (gptel-otel-start-span
               "test" nil (and payload `(("input" . ,(gptel-otel-value-string payload)))))))
    (gptel-otel-end-span span)
    (gptel-otel-export-request (list span))))

(ert-deftest gptel-otel-queue-persists-private-and-replays ()
  (gptel-otel-test--with-spool
   (let ((gptel-otel-delivery-function (lambda (_payload _callback) nil)))
     (let ((file (gptel-otel-enqueue (gptel-otel-test--request "full"))))
       (when gptel-otel--delivery-active
         (gptel-otel--release-lease (plist-get gptel-otel--delivery-active :lease))
         (setq gptel-otel--delivery-active nil))
       (should (file-exists-p file))
       (should (= #o600 (file-modes file)))
       (should (= #o700 (file-modes dir)))
       (setq gptel-otel--delivery-active nil)
       (let ((gptel-otel-delivery-function
              (lambda (_payload callback) (funcall callback '(:ok t :status 200)))))
         (gptel-otel-replay)
         (should-not (file-exists-p file)))))))

(ert-deftest gptel-otel-oversized-langfuse-is-preserved-permanent ()
  (gptel-otel-test--with-spool
   (let ((gptel-otel-endpoint-kind 'langfuse)
         (gptel-otel-cloud-max-bytes 100))
     (let ((file (gptel-otel-enqueue (gptel-otel-test--request (make-string 500 ?x)))))
       (should (file-exists-p file))
       (should (= 1 (plist-get (gptel-otel-status) :permanent)))
       (should (string-match-p (make-string 50 ?x)
                               (with-temp-buffer (insert-file-contents file) (buffer-string))))))))

(ert-deftest gptel-otel-retry-classification-and-backoff ()
  (dolist (code '(429 502 503 504)) (should (gptel-otel-retryable-p code)))
  (should (gptel-otel-retryable-p nil t))
  (should-not (gptel-otel-retryable-p 400))
  (should (= 17 (gptel-otel--retry-delay 4 "17")))
  (let ((gptel-otel-retry-base-seconds 2) (gptel-otel-retry-max-seconds 10))
    (should (= 8 (gptel-otel--retry-delay 3 nil)))
    (should (= 10 (gptel-otel--retry-delay 9 nil)))))

(ert-deftest gptel-otel-langfuse-endpoint-and-headers ()
  (let ((gptel-otel-endpoint-kind 'langfuse)
        (gptel-otel-langfuse-base-url "https://cloud.langfuse.com/")
        (gptel-otel-langfuse-auth-function (lambda () '("pk" . "sk"))))
    (should (equal "https://cloud.langfuse.com/api/public/otel/v1/traces"
                   (gptel-otel--endpoint)))
    (let ((headers (gptel-otel-http-headers)))
      (should (equal "application/json" (cdr (assoc "Content-Type" headers))))
      (should (equal "4" (cdr (assoc "x-langfuse-ingestion-version" headers))))
      (should (equal (concat "Basic " (base64-encode-string "pk:sk" t))
                     (cdr (assoc "Authorization" headers)))))))

(ert-deftest gptel-otel-auth-source-uses-matched-user-as-public-key ()
  (let ((gptel-otel-endpoint-kind 'langfuse)
        (gptel-otel-endpoint "https://example.test/v1/traces")
        (gptel-otel-auth-source-user nil)
        (gptel-otel-auth-source-account "production") query)
    (cl-letf (((symbol-function 'auth-source-search)
               (lambda (&rest args)
                 (setq query args)
                 (list (list :user "pk-real" :secret (lambda () "sk-real"))))))
      (should (equal '("pk-real" . "sk-real")
                     (gptel-otel-langfuse-auth-source)))
      (should (equal "production" (plist-get query :account)))
      (should (equal "https" (plist-get query :port)))
      (should-not (plist-member query :user)))))

(ert-deftest gptel-otel-reserved-headers-are-deduplicated ()
  (let ((gptel-otel-endpoint-kind 'langfuse)
        (gptel-otel-langfuse-auth-function (lambda () '("pk" . "sk")))
        (gptel-otel-headers-function
         (lambda () '(("content-type" . "bad") ("Authorization" . "bad")
                      ("X-Langfuse-Ingestion-Version" . "bad") ("X-Extra" . "yes")))))
    (let ((headers (gptel-otel-http-headers)))
      (should (= 1 (cl-count "content-type" headers :key (lambda (h) (downcase (car h)))
                             :test #'equal)))
      (should (= 1 (cl-count "authorization" headers :key (lambda (h) (downcase (car h)))
                             :test #'equal)))
      (should (= 1 (cl-count "x-langfuse-ingestion-version" headers
                             :key (lambda (h) (downcase (car h))) :test #'equal)))
      (should (equal "yes" (cdr (assoc "X-Extra" headers)))))))

(ert-deftest gptel-otel-unicode-bytes-persist-literally ()
  (gptel-otel-test--with-spool
   (let ((gptel-otel-delivery-function (lambda (_payload _callback) nil))
         (gptel-otel-endpoint-kind 'langfuse)
         (gptel-otel-cloud-max-bytes 1)
         (text "snowman ☃"))
     (let* ((file (gptel-otel-enqueue (gptel-otel-test--request text)))
            (bytes (with-temp-buffer
                     (set-buffer-multibyte nil)
                     (insert-file-contents-literally file)
                     (buffer-string))))
       (should (string-match-p (regexp-quote (encode-coding-string text 'utf-8)) bytes))
       (should (= (length bytes) (plist-get (gptel-otel--read-meta file) :bytes)))))))

(ert-deftest gptel-otel-atomic-claim-and-stale-lease-recovery ()
  (gptel-otel-test--with-spool
   (let ((gptel-otel-delivery-function (lambda (_payload _callback) nil))
         (gptel-otel-endpoint-kind 'langfuse)
         (gptel-otel-cloud-max-bytes 1))
     (let* ((file (gptel-otel-enqueue (gptel-otel-test--request)))
            (meta (gptel-otel--read-meta file))
            (_ (progn (setq meta (plist-put meta :state 'pending))
                      (gptel-otel--write-meta file meta)))
            (lease (gptel-otel--claim-next)))
       (should lease)
       (should-not (file-exists-p file))
       (should-not (gptel-otel--claim-next))
       (set-file-times lease (seconds-to-time 0))
       (let ((gptel-otel-lease-timeout-seconds 1))
         (gptel-otel--recover-stale-leases))
       (should (file-exists-p file))))))

(ert-deftest gptel-otel-watchdog-recovers-and-ignores-late-callback ()
  (gptel-otel-test--with-spool
   (let (callback)
     (let ((gptel-otel-delivery-function
            (lambda (_payload cb) (setq callback cb))))
       (let ((file (gptel-otel-enqueue (gptel-otel-test--request))))
         (should gptel-otel--delivery-active)
         (let* ((active gptel-otel--delivery-active)
                (token (plist-get active :token)) (lease (plist-get active :lease)))
           (gptel-otel--delivery-timeout token lease)
           (should-not gptel-otel--delivery-active)
           (should (file-exists-p file))
           (funcall callback '(:ok t :status 200))
           (should (file-exists-p file))))))))

(ert-deftest gptel-otel-replay-revalidates-oversize-reason ()
  (gptel-otel-test--with-spool
   (let ((gptel-otel-endpoint-kind 'langfuse)
         (gptel-otel-cloud-max-bytes 100))
     (let ((file (gptel-otel-enqueue (gptel-otel-test--request (make-string 500 ?x)))))
       (gptel-otel-replay t)
       (let ((meta (gptel-otel--read-meta file)))
         (should (eq 'permanent (plist-get meta :state)))
         (should (equal "payload exceeds endpoint size limit" (plist-get meta :error))))))))

(ert-deftest gptel-otel-queue-no-empty-envelope ()
  (gptel-otel-test--with-spool (should-not (gptel-otel-enqueue nil))))

(provide 'gptel-otel-transport-test)
