;;; gptel-otel-transport-test.el --- Transport tests  -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'gptel-otel-transport)

(defmacro gptel-otel-test--with-spool (&rest body)
  `(let* ((dir (make-temp-file "gptel-otel-test" t))
          (gptel-otel-spool-directory dir)
          (gptel-otel--delivery-active nil)
          (gptel-otel--delivery-timer nil)
          (gptel-otel--watchdog-timer nil))
     (unwind-protect (progn ,@body)
       (when (timerp gptel-otel--delivery-timer) (cancel-timer gptel-otel--delivery-timer))
       (when (timerp gptel-otel--watchdog-timer) (cancel-timer gptel-otel--watchdog-timer))
       (delete-directory dir t))))

(defun gptel-otel-test--request (&optional payload)
  (let ((span (gptel-otel-start-span
               "test" nil (and payload `(("input" . ,(gptel-otel-value-string payload)))))))
    (gptel-otel-end-span span)
    (gptel-otel-export-request (list span))))

(defun gptel-otel-test--ended-span (name payload &optional parent)
  (let ((span (gptel-otel-start-span
               name parent `(("payload" . ,(gptel-otel-value-string payload))))))
    (gptel-otel-end-span span)
    span))

(defun gptel-otel-test--request-spans (file)
  (let* ((request (json-parse-string
                   (with-temp-buffer (insert-file-contents file) (buffer-string))
                   :object-type 'alist :array-type 'list :null-object nil
                   :false-object :json-false))
         (resource (car (alist-get 'resourceSpans request)))
         (scope (car (alist-get 'scopeSpans resource))))
    (alist-get 'spans scope)))

(ert-deftest gptel-otel-queue-persists-private-and-replays ()
  (gptel-otel-test--with-spool
   (let ((gptel-otel-delivery-function (lambda (_payload _callback) nil)))
     (let ((file (gptel-otel-enqueue (gptel-otel-test--request "full"))))
       (when gptel-otel--delivery-active
         (gptel-otel--release-lease (plist-get gptel-otel--delivery-active :lease))
         (setq gptel-otel--delivery-active nil))
       (should (file-exists-p file))
       (should (= #o600 (file-modes file)))
       (should (= #o700 (file-modes dir)))
       (setq gptel-otel--delivery-active nil)
       (let ((gptel-otel-delivery-function
              (lambda (_payload callback) (funcall callback '(:ok t :status 200)))))
         (gptel-otel-replay)
         (should-not (file-exists-p file)))))))

(ert-deftest gptel-otel-oversized-langfuse-is-preserved-permanent ()
  (gptel-otel-test--with-spool
   (let ((gptel-otel-endpoint-kind 'langfuse)
         (gptel-otel-cloud-max-bytes 100))
     (let ((file (gptel-otel-enqueue (gptel-otel-test--request (make-string 500 ?x)))))
       (should (file-exists-p file))
       (should (= 1 (plist-get (gptel-otel-status) :permanent)))
       (should (string-match-p (make-string 50 ?x)
                               (with-temp-buffer (insert-file-contents file) (buffer-string))))))))

(ert-deftest gptel-otel-retry-classification-and-backoff ()
  (dolist (code '(429 502 503 504)) (should (gptel-otel-retryable-p code)))
  (should (gptel-otel-retryable-p nil t))
  (should-not (gptel-otel-retryable-p 400))
  (should (= 17 (gptel-otel--retry-delay 4 "17")))
  (let ((gptel-otel-retry-base-seconds 2) (gptel-otel-retry-max-seconds 10))
    (should (= 8 (gptel-otel--retry-delay 3 nil)))
    (should (= 10 (gptel-otel--retry-delay 9 nil)))))

(ert-deftest gptel-otel-langfuse-endpoint-and-headers ()
  (let ((gptel-otel-endpoint-kind 'langfuse)
        (gptel-otel-langfuse-base-url "https://cloud.langfuse.com/")
        (gptel-otel-langfuse-auth-function (lambda () '("pk" . "sk"))))
    (should (equal "https://cloud.langfuse.com/api/public/otel/v1/traces"
                   (gptel-otel--endpoint)))
    (let ((headers (gptel-otel-http-headers)))
      (should (equal "application/json" (cdr (assoc "Content-Type" headers))))
      (should (equal "4" (cdr (assoc "x-langfuse-ingestion-version" headers))))
      (should (equal (concat "Basic " (base64-encode-string "pk:sk" t))
                     (cdr (assoc "Authorization" headers)))))))

(ert-deftest gptel-otel-auth-source-uses-matched-user-as-public-key ()
  (let ((gptel-otel-endpoint-kind 'langfuse)
        (gptel-otel-endpoint "https://example.test/v1/traces")
        (gptel-otel-auth-source-user nil)
        (gptel-otel-auth-source-account "production") query)
    (cl-letf (((symbol-function 'auth-source-search)
               (lambda (&rest args)
                 (setq query args)
                 (list (list :user "pk-real" :secret (lambda () "sk-real"))))))
      (should (equal '("pk-real" . "sk-real")
                     (gptel-otel-langfuse-auth-source)))
      (should (equal "production" (plist-get query :account)))
      (should (equal "https" (plist-get query :port)))
      (should-not (plist-member query :user)))))

(ert-deftest gptel-otel-reserved-headers-are-deduplicated ()
  (let ((gptel-otel-endpoint-kind 'langfuse)
        (gptel-otel-langfuse-auth-function (lambda () '("pk" . "sk")))
        (gptel-otel-headers-function
         (lambda () '(("content-type" . "bad") ("Authorization" . "bad")
                      ("X-Langfuse-Ingestion-Version" . "bad") ("X-Extra" . "yes")))))
    (let ((headers (gptel-otel-http-headers)))
      (should (= 1 (cl-count "content-type" headers :key (lambda (h) (downcase (car h)))
                             :test #'equal)))
      (should (= 1 (cl-count "authorization" headers :key (lambda (h) (downcase (car h)))
                             :test #'equal)))
      (should (= 1 (cl-count "x-langfuse-ingestion-version" headers
                             :key (lambda (h) (downcase (car h))) :test #'equal)))
      (should (equal "yes" (cdr (assoc "X-Extra" headers)))))))

(ert-deftest gptel-otel-generic-authorization-and-custom-headers-pass-through ()
  (let ((gptel-otel-backend-profile 'otlp-http)
        (gptel-otel-headers-function
         (lambda () '(("Authorization" . "Bearer token")
                      ("x-honeycomb-team" . "team")
                      ("X-Tenant-ID" . "tenant")
                      ("authorization" . "Basic ignored")))))
    (let ((headers (gptel-otel-http-headers)))
      (should (equal "Bearer token" (cdr (assoc "Authorization" headers))))
      (should (equal "team" (cdr (assoc "x-honeycomb-team" headers))))
      (should (equal "tenant" (cdr (assoc "X-Tenant-ID" headers))))
      (should (= 1 (cl-count "authorization" headers
                             :key (lambda (h) (downcase (car h))) :test #'equal))))))

(ert-deftest gptel-otel-langfuse-required-headers-win-and-dedupe ()
  (let ((gptel-otel-backend-profile 'langfuse)
        (gptel-otel-langfuse-auth-function (lambda () '("pk" . "sk")))
        (gptel-otel-headers-function
         (lambda () '(("Authorization" . "Bearer bad")
                      ("X-Langfuse-Ingestion-Version" . "bad")
                      ("X-Tenant" . "kept")))))
    (let ((headers (gptel-otel-http-headers)))
      (should (equal (concat "Basic " (base64-encode-string "pk:sk" t))
                     (cdr (assoc "Authorization" headers))))
      (should (equal "4" (cdr (assoc "x-langfuse-ingestion-version" headers))))
      (should (equal "kept" (cdr (assoc "X-Tenant" headers)))))))

(ert-deftest gptel-otel-generic-byte-limit-is-enforced ()
  (gptel-otel-test--with-spool
   (let ((gptel-otel-backend-profile 'otlp-http)
         (gptel-otel-generic-max-bytes 100))
     (let ((file (gptel-otel-enqueue
                  (gptel-otel-test--request (make-string 500 ?x)))))
       (should (eq 'permanent (plist-get (gptel-otel--read-meta file) :state)))))))

(ert-deftest gptel-otel-trace-batches-by-encoded-bytes-preserving-tree ()
  (gptel-otel-test--with-spool
   (let* ((gptel-otel-backend-profile 'otlp-http)
          (gptel-otel-generic-batch-target-bytes 950)
          (gptel-otel-generic-max-bytes 1200)
          (gptel-otel-delivery-function (lambda (&rest _)))
          (root (gptel-otel-test--ended-span "root" (make-string 120 ?r)))
          (child-a (gptel-otel-test--ended-span "a" (make-string 120 ?a) root))
          (child-b (gptel-otel-test--ended-span "b" (make-string 120 ?b) root))
          (spans (list root child-a child-b))
          (files (gptel-otel-enqueue-spans spans)))
     (when gptel-otel--delivery-active
       (gptel-otel--release-lease (plist-get gptel-otel--delivery-active :lease))
       (setq gptel-otel--delivery-active nil))
     (should (> (length files) 1))
     (let ((ids nil) (parents nil) (trace-ids nil)
           (group-ids nil) (counts nil) (indexes nil))
       (dolist (file files)
         (should (< (file-attribute-size (file-attributes file))
                    gptel-otel-generic-max-bytes))
         (let ((meta (gptel-otel--read-meta file)))
           (push (plist-get meta :export-group-id) group-ids)
           (push (plist-get meta :batch-count) counts)
           (push (plist-get meta :batch-index) indexes))
         (dolist (span-json (gptel-otel-test--request-spans file))
           (push (alist-get 'spanId span-json) ids)
           (push (alist-get 'traceId span-json) trace-ids)
           (when (alist-get 'parentSpanId span-json)
             (push (cons (alist-get 'spanId span-json)
                         (alist-get 'parentSpanId span-json)) parents))))
       (should (= 3 (length ids)))
       (should (= 3 (length (delete-dups (copy-sequence ids)))))
       (should (= 1 (length (delete-dups trace-ids))))
       (should (= 1 (length (delete-dups group-ids))))
       (should (equal (number-sequence 0 (1- (length files))) (sort indexes #'<)))
       (should (cl-every (lambda (count) (= count (length files))) counts))
       (should (equal (gptel-otel-span-span-id root)
                      (cdr (assoc (gptel-otel-span-span-id child-a) parents))))
       (should (equal (gptel-otel-span-span-id root)
                      (cdr (assoc (gptel-otel-span-span-id child-b) parents))))))))

(ert-deftest gptel-otel-single-oversized-span-is-retained-permanent ()
  (gptel-otel-test--with-spool
   (let* ((gptel-otel-backend-profile 'otlp-http)
          (gptel-otel-generic-batch-target-bytes 500)
          (gptel-otel-generic-max-bytes 600)
          (span (gptel-otel-test--ended-span "huge" (make-string 2000 ?z)))
          (file (car (gptel-otel-enqueue-spans (list span))))
          (meta (gptel-otel--read-meta file)))
     (should (file-exists-p file))
     (should (eq 'permanent (plist-get meta :state)))
     (should (equal (gptel-otel-span-span-id span)
                    (plist-get meta :oversize-span-id)))
     (should (string-match-p (make-string 100 ?z)
                             (with-temp-buffer
                               (insert-file-contents file) (buffer-string)))))))

(ert-deftest gptel-otel-group-enqueue-failure-rolls-back-and-reports-failure ()
  (gptel-otel-test--with-spool
   (let* ((gptel-otel-backend-profile 'otlp-http)
          (gptel-otel-generic-batch-target-bytes 800)
          (spans (list (gptel-otel-test--ended-span "a" (make-string 200 ?a))
                       (gptel-otel-test--ended-span "b" (make-string 200 ?b))))
          (writes 0)
          (real-write (symbol-function 'gptel-otel--atomic-write)))
     (cl-letf (((symbol-function 'gptel-otel--atomic-write)
                (lambda (file content &optional literal)
                  (setq writes (1+ writes))
                  (if (= writes 4) (error "injected group failure")
                    (funcall real-write file content literal)))))
       (should-not (gptel-otel-enqueue-spans spans)))
     (should-not (directory-files dir nil "\\.json\\|\\.meta")))))

(ert-deftest gptel-otel-queue-destination-mismatch-is-visible ()
  (gptel-otel-test--with-spool
   (let ((gptel-otel-backend-profile 'otlp-http)
         (gptel-otel-endpoint "https://one.test/v1/traces")
         (gptel-otel-delivery-function (lambda (&rest _))))
     (let ((file (gptel-otel-enqueue (gptel-otel-test--request))))
       (when gptel-otel--delivery-active
         (gptel-otel--release-lease (plist-get gptel-otel--delivery-active :lease))
         (setq gptel-otel--delivery-active nil))
       (let ((gptel-otel-endpoint "https://two.test/v1/traces"))
         (should-not (gptel-otel--claim-next))
         (let ((meta (gptel-otel--read-meta file)))
           (should (eq 'mismatched (plist-get meta :state)))
           (should (string-match-p "destination mismatch" (plist-get meta :error)))
           (should (= 1 (plist-get (gptel-otel-status) :mismatched)))))))))

(ert-deftest gptel-otel-same-endpoint-different-account-is-mismatched ()
  (gptel-otel-test--with-spool
   (let ((gptel-otel-backend-profile 'otlp-http)
         (gptel-otel-endpoint "https://collector.test/v1/traces")
         (gptel-otel-generic-account-id "tenant-a")
         (gptel-otel-delivery-function (lambda (&rest _))))
     (let ((file (gptel-otel-enqueue (gptel-otel-test--request))))
       (when gptel-otel--delivery-active
         (gptel-otel--release-lease (plist-get gptel-otel--delivery-active :lease))
         (setq gptel-otel--delivery-active nil))
       (let ((gptel-otel-generic-account-id "tenant-b"))
         (should-not (gptel-otel--claim-next))
         (should (eq 'mismatched
                     (plist-get (gptel-otel--read-meta file) :state))))))))

(ert-deftest gptel-otel-legacy-queue-requires-explicit-migration ()
  (gptel-otel-test--with-spool
   (let ((gptel-otel-delivery-function (lambda (&rest _))))
     (gptel-otel--ensure-spool)
     (let* ((file (expand-file-name "legacy.json" dir))
            (meta (gptel-otel--metadata-file file))
            (destination-id (plist-get (gptel-otel--destination) :destination-id)))
       (gptel-otel--write-private file "{}" t)
       (gptel-otel--write-private meta "(:attempts 0 :state pending)")
       (should-not (gptel-otel--claim-next))
       (should-error (gptel-otel-migrate-legacy-queue "wrong"))
       (should (= 1 (gptel-otel-migrate-legacy-queue destination-id)))
       (should (equal destination-id
                      (plist-get (gptel-otel--read-meta file) :destination-id)))))))

(ert-deftest gptel-otel-otlp-partial-success-is-preserved ()
  (let ((result (gptel-otel--default-response-interpreter
                 '(:ok t :status 200
                   :body "{\"partialSuccess\":{\"rejectedSpans\":2,\"errorMessage\":\"bad spans\"}}"))))
    (should-not (plist-get result :ok))
    (should (plist-get result :partial))
    (should (= 2 (plist-get result :rejected-spans)))
    (should (equal "bad spans" (plist-get result :error)))))

(ert-deftest gptel-otel-otlp-partial-success-zero-and-snake-case ()
  (should (plist-get
           (gptel-otel--default-response-interpreter
            '(:ok t :status 200 :body "{\"partialSuccess\":{\"rejectedSpans\":0}}"))
           :ok))
  (let ((result (gptel-otel--default-response-interpreter
                 '(:ok t :status 200
                   :body "{\"partial_success\":{\"rejected_spans\":\"3\",\"error_message\":\"bad\"}}"))))
    (should (plist-get result :partial))
    (should (equal "3" (plist-get result :rejected-spans)))))

(ert-deftest gptel-otel-profile-is-extensible ()
  (let* ((profile (gptel-otel-make-backend-profile
                   :name 'community
                   :endpoint-function (lambda () "https://community.test/traces")
                   :headers-function (lambda () '(("X-Community" . "yes")))
                   :max-bytes-function (lambda () 123)
                   :response-function #'identity
                   :destination-id-function
                   (lambda (_profile _endpoint) "community:stable")))
         (gptel-otel-backend-profile profile))
    (should (equal "https://community.test/traces" (gptel-otel--endpoint)))
    (should (= 123 (gptel-otel--max-request-bytes)))
    (should (equal "community:stable"
                   (plist-get (gptel-otel--destination) :destination-id)))
    (should (equal "yes" (cdr (assoc "X-Community" (gptel-otel-http-headers)))))))

(ert-deftest gptel-otel-unicode-bytes-persist-literally ()
  (gptel-otel-test--with-spool
   (let ((gptel-otel-delivery-function (lambda (_payload _callback) nil))
         (gptel-otel-endpoint-kind 'langfuse)
         (gptel-otel-cloud-max-bytes 1)
         (text "snowman ☃"))
     (let* ((file (gptel-otel-enqueue (gptel-otel-test--request text)))
            (bytes (with-temp-buffer
                     (set-buffer-multibyte nil)
                     (insert-file-contents-literally file)
                     (buffer-string))))
       (should (string-match-p (regexp-quote (encode-coding-string text 'utf-8)) bytes))
       (should (= (length bytes) (plist-get (gptel-otel--read-meta file) :bytes)))))))

(ert-deftest gptel-otel-atomic-claim-and-stale-lease-recovery ()
  (gptel-otel-test--with-spool
   (let ((gptel-otel-delivery-function (lambda (_payload _callback) nil))
         (gptel-otel-endpoint-kind 'langfuse)
         (gptel-otel-cloud-max-bytes 1))
     (let* ((file (gptel-otel-enqueue (gptel-otel-test--request)))
            (meta (gptel-otel--read-meta file))
            (_ (progn (setq meta (plist-put meta :state 'pending))
                      (gptel-otel--write-meta file meta)))
            (lease (gptel-otel--claim-next)))
       (should lease)
       (should-not (file-exists-p file))
       (should-not (gptel-otel--claim-next))
       (set-file-times lease (seconds-to-time 0))
       (let ((gptel-otel-lease-timeout-seconds 1))
         (gptel-otel--recover-stale-leases))
       (should (file-exists-p file))))))

(ert-deftest gptel-otel-watchdog-recovers-and-ignores-late-callback ()
  (gptel-otel-test--with-spool
   (let (callback)
     (let ((gptel-otel-delivery-function
            (lambda (_payload cb) (setq callback cb))))
       (let ((file (gptel-otel-enqueue (gptel-otel-test--request))))
         (should gptel-otel--delivery-active)
         (let* ((active gptel-otel--delivery-active)
                (token (plist-get active :token)) (lease (plist-get active :lease)))
           (gptel-otel--delivery-timeout token lease)
           (should-not gptel-otel--delivery-active)
           (should (file-exists-p file))
           (funcall callback '(:ok t :status 200))
           (should (file-exists-p file))))))))

(ert-deftest gptel-otel-replay-revalidates-oversize-reason ()
  (gptel-otel-test--with-spool
   (let ((gptel-otel-endpoint-kind 'langfuse)
         (gptel-otel-cloud-max-bytes 100))
     (let ((file (gptel-otel-enqueue (gptel-otel-test--request (make-string 500 ?x)))))
       (gptel-otel-replay t)
       (let ((meta (gptel-otel--read-meta file)))
         (should (eq 'permanent (plist-get meta :state)))
         (should (equal "payload exceeds endpoint size limit" (plist-get meta :error))))))))

(ert-deftest gptel-otel-queue-no-empty-envelope ()
  (gptel-otel-test--with-spool (should-not (gptel-otel-enqueue nil))))

(ert-deftest gptel-otel-multibatch-group-delivers-every-member ()
  (gptel-otel-test--with-spool
   (let ((gptel-otel-backend-profile 'otlp-http)
         (gptel-otel-endpoint "https://collector.test/v1/traces")
         (gptel-otel-generic-batch-target-bytes 900)
         (gptel-otel-generic-max-bytes 1400)
         callbacks delivered)
     (let ((gptel-otel-delivery-function
            (lambda (payload callback)
              (push payload delivered)
              (setq callbacks (append callbacks (list callback))))))
       (let* ((root (gptel-otel-test--ended-span "root" (make-string 180 ?r)))
              (a (gptel-otel-test--ended-span "a" (make-string 180 ?a) root))
              (b (gptel-otel-test--ended-span "b" (make-string 180 ?b) root))
              (files (gptel-otel-enqueue-spans (list root a b)))
              (group-id (plist-get (gptel-otel--read-meta (car files))
                                   :export-group-id))
              (marker (gptel-otel--group-marker-file group-id)))
         (should (> (length files) 1))
         (should (file-exists-p marker))
         (while (or callbacks gptel-otel--delivery-active)
           (when callbacks
             (let ((callback (pop callbacks)))
               (funcall callback '(:ok t :status 200))))
           (when (timerp gptel-otel--delivery-timer)
             (cancel-timer gptel-otel--delivery-timer)
             (setq gptel-otel--delivery-timer nil))
           (unless gptel-otel--delivery-active (gptel-otel-flush)))
         (should (= (length files) (length delivered)))
         (dolist (file files) (should-not (file-exists-p file)))
         (should-not (file-exists-p marker)))))))

(ert-deftest gptel-otel-incomplete-group-marker-blocks-delivery ()
  (gptel-otel-test--with-spool
   (let ((gptel-otel-delivery-function (lambda (&rest _) (error "must not send"))))
     (gptel-otel--ensure-spool)
     (let* ((file (expand-file-name "incomplete.json" dir))
            (destination (gptel-otel--destination))
            (meta (append '(:attempts 0 :state pending
                            :export-group-id "incomplete" :batch-count 2)
                          destination)))
       (gptel-otel--write-private file "{}" t)
       (gptel-otel--write-meta file meta)
       (should-not (gptel-otel--claim-next
                    (plist-get destination :destination-id)))
       (should (file-exists-p file))))))

(ert-deftest gptel-otel-purge-queue-removes-only-selected-terminal-states ()
  (gptel-otel-test--with-spool
   (gptel-otel--ensure-spool)
   (let ((mismatch (expand-file-name "mismatch.json" dir))
         (pending (expand-file-name "pending.json" dir)))
     (dolist (file (list mismatch pending))
       (gptel-otel--write-private file "{}" t))
     (gptel-otel--write-meta mismatch '(:state mismatched :attempts 0))
     (gptel-otel--write-meta pending '(:state pending :attempts 0))
     (should (= 1 (gptel-otel-purge-queue '(mismatched))))
     (should-not (file-exists-p mismatch))
     (should (file-exists-p pending))
     (should-error (gptel-otel-purge-queue '(pending))))))

(provide 'gptel-otel-transport-test)
